### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongma7** [openshift/efs-provisioner-operator#1]
- [ ] Tests (https://github.com/operator-framework/operator-sdk/issues/536)
- [x] Manually clean up cluster resources (use finalizer)
- [x] Respect spec.ManagementState
- [x] Finalize group name: ~efs.provisioner.storage.openshift.io? provisioner.storage.openshift.io?~ efs.storage.openshift.io
- [x] Move validation to CRD
- [x] Write ClusterServiceVersion https://github.com/openshift/efs-provisioner-operator/commit/b46047a5774b98534b576e9fdee2db4a02a6bff0#diff-bd95c819dabdf0956f976032d6dd5df6
- [ ] SC.mountOptions
- [ ] Follow image pattern (rhel multi-stage, drop default operator-sdk things like alpine, build/_output, etc.)
- [ ] Context timeouts
- [ ] DNSName OR FSID+Region validation
